### ISSUE TITLE
使用`D435i`建图， mesh达不到预期效果

### ISSUE THREAD

**Issue by 1qingfeng-1** [SYSU-STAR/H2-Mapping#25]
## 程序修改

- 替换mapping.py 118行如下，, 修复`conda python3`环境下无法使用cv_bridge

  ```python
  update_pose = True
          color_image = np.frombuffer(color.data, dtype=np.uint8).reshape(color.height, color.width, -1)
          depth_image = np.frombuffer(depth.data, dtype=np.uint16).reshape(depth.height, depth.width, -1)
          depth_image = np.squeeze(depth_image)
  ```

## 参数修改

- 修改`configs/realsense/realsense.yaml`

  ```yaml
  # 通过 rostopic echo /camera/color/camera_info 查询D435i 内参K
  intrinsic: [ 607.9873046875, 607.9636840820312, 318.7456970214844, 248.21688842773438 ]
  
  # GPU内存只有8GB可用，所以batch_size调小，能跑40轮
  N_rays_each: 4096 # mapping's sampling ray
  batch_size: 256
  num_vertexes: 200000
  ```

- 新建`configs/realsense/d435i.yaml`

  ```yaml
  base_config: configs/realsense/realsense.yaml
  
  exp_name: realsense/d435i
  
  data_specs:
    max_depth: 3
    use_gt: True # notice
  
  decoder_specs:
    bound: [ [ 0.0, 10.0 ],[ 0.0, 10.0 ],[ 0.0, 5.0 ] ] # [x_min,x_max],[y_min,y_max],[z_min,z_max]
  ```

- 修改`src/dvins/config/uav2022/uav_nerf.yaml`

  - 通过 rs-enumerate-devices -c 查询参数
  
   ```text
    Intrinsic of "Color" / 640x480 {YUYV/RGB8/BGR8/RGBA8/BGRA8/Y8/Y16}
      Width:        640
      Height:       480
      PPX:          318.745697021484
      PPY:          248.216888427734
      Fx:           607.9873046875
      Fy:           607.963684082031
   ```
  修改替换
  ```yaml
  projection_parameters:
     # fx: 607.987243652344
     # fy: 607.963684082031
     # cx: 422.745697021484
     # cy: 248.216888427734
  
     # 640 x 480  
     fx: 607.9873046875   # FX
     fy: 607.963684082031 # Fy
     cx: 318.745697021484	# cx
     cy: 248.216888427734 # cy
     
     
  ```
  通过 rs-enumerate-devices -c 查询参数
  
  ```text
  Extrinsic from "Color"    To      "Gyro" :
   Rotation Matrix:
     0.999841        -0.0178037        0.00055596    
     0.0178052        0.999837        -0.00294401    
    -0.000503456      0.00295344       0.999996      
  
   Translation Vector: -0.0201705582439899  0.00509376963600516  0.0112307714298368  
  ```
  
  然后是修改旋转平移参数 
  
  ```yaml
  extrinsicRotation: !!opencv-matrix
     rows: 3
     cols: 3
     dt: d
     data: [ 0.999841, -0.0178037, 0.00055596,   
           0.0178052, 0.999837, -0.00294401,    
        -0.000503456, 0.00295344, 0.99999]
  
  #Translation from camera frame to imu frame, imu^T_cam
  extrinsicTranslation: !!opencv-matrix
     rows: 3
     cols: 1
     dt: d
     data: [-0.0201705582439899,  0.00509376963600516,  0.0112307714298368]
  ```

## 运行程序

```bash
python3 -W ignore demo/run_mapping.py configs/realsense/d435i.yaml -run_ros

./ros_cmd/run_vins_rgbd.sh

rosbag play d435i_h2_mapping.bag
```

## 最终效果

![image](https://github.com/SYSU-STAR/H2-Mapping/assets/33478786/ef6a3cd6-2d3c-47dd-8d2d-6173612e1bea)

![image](https://github.com/SYSU-STAR/H2-Mapping/assets/33478786/bdeddc9b-3bc8-4088-b020-dc1b272166f7)

## 我错过了什么重要的步骤吗

- 需要帮助

- 我的GPU只有8GB RAM
